package com.atmosg.windai.vo.metar.type;

public enum MetarField {
  STATION_ICAO,
  REPORT_TYPE,
  OBSERVATION_TIME,
  REPORT_TIME,
  WIND,
  VISIBILITY,
  TEMPERATURE_PAIR,
  ALTIMETER,
  WEATHER,
  WEATHER_GROUP,
  CLOUD,
  CLOUD_GROUP,
  REMARKS;
}
